### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by Sorurus** [PF2M/Indigo#1]
Registering through [indigo.cafe/login](indigo.cafe/login) and clicking the "if you don't have an account, sign up here" brings you to [indigo.cafe/signup](indigo.cafe/signup) which just is the homepage.

**Comment by ashenAshley** [comment]
signups were closed and still are :3

**Comment by OhHeyItsPip** [comment]
The site's dead lol

**Comment by kamilthecitratester** [comment]
thats why its rehostable.

**Comment by ariankordi** [comment]
good
