### ISSUE TITLE
go run *.go

### ISSUE THREAD

**Issue by thatNapoleonDude** [PF2M/Indigo#7]
tried to run indigo, the output is `listening on :8000` but nothing displays on localhost:8000/127.0.0.1:8000.

**Comment by thatNapoleonDude** [comment]
Also, I tried on both Windows and Ubuntu 20.04. Nothing.

**Comment by PF2M** [comment]
this is intended functionality i swear

**Comment by OhHeyItsPip** [comment]
It's not a bug, it's a feature.

**Comment by kamilthecitratester** [comment]
u have to do port: 127.0.0.1:8000 for it to run on port 8000
