### ISSUE TITLE
error when setting up requirements

### ISSUE THREAD

**Issue by minihoot** [PF2M/Indigo#9]
when setting up requirements, it says `go: warning: github.com/microcosm-cc/bluemonday@v1.0.23: retracted by module author: Retract older versions as only latest is to be depended upon
go: to switch to the latest unretracted version, run:
        go get github.com/microcosm-cc/bluemonday@latest`

**Comment by ariankordi** [comment]
So it looks like they retracted all versions of bluemonday before 1.0.24, which is a version they released right before I stopped working on this for a little while.
It's not a huge deal, it tells you exactly how to fix it but I'm going to fix this next time I push anything, which might be soon.

**Comment by minihoot** [comment]
ok nice

**Comment by minihoot** [comment]
actually ill just reopen this so you'll be reminded
